### ISSUE TITLE
Les droits des administrateurs et secrétaire

### ISSUE THREAD

**Issue by chagry** [williamtheaux/APSO#1]
## Les droits des administrateurs et secrétaire

```
Les administrateurs sont au nombre de deux : un Master et un Secrétaire. Les droits du Master dominent ceux du secrétaire ; les actions du Secrétaire doivent être validées par le Master. Secrétaire et Master peuvent : = Ajouter des postes pour les élections (par défaut, 4 postes sont déjà créés : Président, Vice-Président, Secrétaire, Trésorier).

= Valider ou invalider les membres.

= Supprimer et mettre en forme des lois et leurs variations.
```

Si les droits du Master dominent ceux du secrétaire et les actions du Secrétaire doivent être validées par le Master. Sur le plant technique et modulable dans le futur, il serait plus interessant de crée des fonction specifique au poste de secrétaire et accessible uniquement a la personne élu a ce moment la. Les fonction vont permetre au secrétaire de proposer une modification de loi, creation d'un nouveau poste, ou de la supression d'un membre.

Sur le plant futur, il faut travailler ses fonctions associées à un poste, le plus modulable possible pour pouvoir associer d'autre fonction à d'autres postes créés. Ex, comme le système est baser sur le bitcoin, ont pourra toujours crée des fonctions pour le trésorier, qui seront capable de faire des transfert.

**Comment by williamtheaux** [comment]
no comment  (je pense que j'ai répondu/traité cet issue dans issue=Validation ou non, de l'action par un master.
