### ISSUE TITLE
Validation ou non, de l'action par un master.

### ISSUE THREAD

**Issue by chagry** [williamtheaux/APSO#3]
### Pour la validation de l'action par un master, vous avez deux possibilistes.
1. Le Secrétaire effectuer directement la modification dans les données. Sans la validation.
   - Avantage
     - Une liberter pour les utilisateur.
     - Les administrateurs possèdent déjà les fonctions de modification des données en question et un access a l'historique.
   - Inconvénient
     - Le Secrétaire ne pourra pas avoir access a la fonction de suppression de lois, postes.
2. Les actions devraient être validées par un master.
   - Avantage
     - Les actions ne peuvent pas être visibles avant d'être validées.
     - Une bonne sécurité pour l'administration.
   - Inconvénient
     - Développement de fonction supplémentaire pour la validation des actions des secrétaires.

```
Je préfère cette première - parce que a) elle me semble plus simple, plus légère - b) dans les minutes, heures qui suivent la modifPARsecrétaire, le Master peut éventuellement intervenir et corriger la modif - c) et parce qu'il y a toujours le recours à la restauration sur sauvegarde journalière.

(deux questions à vérifier 1) les modifs sont visibles... MAIS y a-t-il aussi une fonction 'alerte' qui informe le Master qu'une modif a été posée  ? ---   2) il y a une sauvegarde journalière et possibilité de restauration... MAIS jusqu'à quel historique remonte la restauration possible (autrement dit - peut-on faire une restauration à jour-moins-trois,  moins-quatre etc... ou bien n'y a-t-il jamais qu'une seule restauration possible (celle de la veille) ?

Par contre je ne comprends pas pourquoi cette solution empêche le Secrétaire à avoir accès à "fonction de suppression de lois, postes"
```

**Comment by chagry** [comment]
Le recours à la restauration sur sauvegarde journalière n'est pas du tout une solution, mais plus tôt une opération lourde qu'il faut pratiquer en dernier recourt. Vous avez 2 semaine en arrière de restauration.

Pour la fonction 'alerte' qui informe le Master, pour l'instant elle n'est pas prévue dans le dev car le module log regroupe déjà des fonction similaire, Il n'est pas nécessaire, des le départ surcharger l'api avec des fonction similaire.

Le Secrétaire ne peut avoir accès à "fonction de suppression de lois, postes ", car vaux mieux prévenir que guérir. Retour en arrière des modifications exigerait un dev plus important est imposant. Le Secrétaire pourra toujours avoir une fonction pour suggérait la suppression d'un membre, mais devra être valider par un master avant l'exécution. Cela revient a développer des validations pour les masters non prévue a la base.

**Comment by williamtheaux** [comment]
En découvrant et prenant l'habitude de l'outil Github, selon ce que je comprends pour l'instant nous sommes sur cette question qui organise l'administration par deux administrateurs : le Master et le Secrétaire. Le Secrétaire a) nomme/dénomme les membres, b) il met en forme les lois, c) il gère la liste des rôles. Ces actions peuvent être observées par tous. On peut craindre qu'il manifeste un comportement égaré ou délinquant. Les risques cependant ne sont pas "énormes" - n'oublions pas que nous sommes dans une démocratie vivante. Au pire elle se suicide - et c'est un phénomène propre au vivant (parfois écologiquement salubre). Mais avant cela, il y a une marge énorme. S'il y a eu une sérieuse catastrophe - la solution sera la restauration (en dernier recours). S'il y a eu une sérieuse faute (par exemple la suppression d'un membre pour cause de conflit personnel) le Master peut corriger la faute (il rétablit le membre, remet en ligne une loi etc..) et la signale à tous les membres dans le forum annexe. De même si la faute est minime, le Master la signale. Alors entre en jeu la démocratie précisément - à savoir que le Secrétaire ne sera probablement plus élu à ce rôle.
A la réflexion sur ce point, il me semble qu'il faille bien évaluer le programme en fonction d'une force vitale agissante. APSO n'est pas un moteur "surdéterminant" - il est susceptible d'un nombre considérable de fautes et cette "machine à gouverner" doit opérer de manière très malléable à la force de ses membres.
Je réitère donc la fonction du secrétaire : a) nomme/dénomme les membres, b) met en forme les lois, c) gère la liste des rôles. Il n'y effectue directement ces opérations qui deviennent actives sans validation. Le Master a les mêmes pouvoirs - et tous les pouvoirs, notamment d'exclure le membre qui abuserait de sa fonction de Secrétaire.
