### ISSUE TITLE
à propos cumul des mandats

### ISSUE THREAD

**Issue by williamtheaux** [williamtheaux/APSO#4]
à propos du traitement des votes 
Nous avons estimé que EN CAS de ballottage , le statut demeure dans l'état antérieur

Par contre EN CAS de cumul - j'avais suggéré que l'on applique cette même règle " si ambiguïté/indécidabilité, on reste à l'anterieur" mais je modifie cette suggestion.
J'écris ce soir une seconde section dans le LivreBlanc où je mentionne la fonction hiérarchique. Il sera bienvenu d'insérer cette fonction hiérarchique à l'occasion du cumul. Donc lorsqu'il y aura cumul, il existera une règle hiérarchique P > S > T > V qui traitera l'ambiguïté. Je souhaite écrire une troisième section demain qui précisera en détail ce sujet.

**Comment by chagry** [comment]
ok pour la fonction hiérarchique. j'attend demain pour les détail.
